-- My Why — "My Mantra" and "My Circle".
-- Run once in the Supabase SQL editor. Idempotent; safe to re-run.

-- ---------- My Mantra ----------
create table if not exists public.why_mantras (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  text        text not null,
  meaning     text default '',
  source      text default '',
  favourite   boolean not null default false,
  created_at  timestamptz not null default now()
);
alter table public.why_mantras enable row level security;
drop policy if exists "own mantras" on public.why_mantras;
create policy "own mantras" on public.why_mantras
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
-- Favourites float to the top, newest first within each group.
create index if not exists why_mantras_user_fav_idx
  on public.why_mantras (user_id, favourite desc, created_at desc);

-- ---------- My Circle ----------
-- band: 'close' (1-5) | 'sympathy' (6-15) | 'affinity' (16-50) | 'network' (51-150)
create table if not exists public.why_circle (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  band        text not null default 'close',
  note        text default '',
  created_at  timestamptz not null default now()
);
alter table public.why_circle enable row level security;
drop policy if exists "own circle" on public.why_circle;
create policy "own circle" on public.why_circle
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists why_circle_user_band_idx
  on public.why_circle (user_id, band, created_at);

-- Per-person page: essay + "moments worth keeping", stored together as JSON:
--   { "essay": "…", "moments": [ { "y": "2019", "t": "He showed up." } ] }
alter table public.why_circle
  add column if not exists page text default '';
